#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleObjCCalendarFoundation-import-private.h
src/reflect/_MulleObjCCalendarFoundation-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleObjCCalendarFoundation-import.h
src/reflect/_MulleObjCCalendarFoundation-include.h
)

set( PUBLIC_HEADERS
src/_MulleGregorianCalendar.h
src/_MulleJulianCalendar.h
src/MulleObjCCalendarFoundation.h
src/MulleObjCLoader+MulleObjCCalendarFoundation.h
src/NSCalendar+NSDate.h
src/NSCalendar.h
src/NSDateComponents.h
src/import.h
)

