#! /bin/sh


get_mulle_kybernetik_gpg_key()
{
   curl -sS "https://www.mulle-kybernetik.com/dists/debian-admin-pub.asc" | \
      sudo apt-key add -

   echo "Added Mulle kybernetiK repository key to apt" >&2
}


add_mulle_kybernetik_to_apt_sources()
{
   local release="$1"
   local debname="$2"

   echo "deb [arch=all] http://www.mulle-kybernetik.com ${release} ${debname}" | \
   sudo tee "/etc/apt/sources.list.d/mulle-kybernetik.com-${debname}.list" > /dev/null

   echo "Added Mulle kybernetiK repository to apt" >&2
}


get_codeon_gpg_key()
{
   curl -sS "https://www.codeon.de/dists/codeon-pub.asc" | \
      sudo apt-key add -

   echo "Added Codeon repository key to apt" >&2
}


add_codeon_to_apt_sources()
{
   local release="$1"
   local debname="$2"

   echo "deb [arch=amd64] http://download.codeon.de ${release} ${debname}" | \
   sudo tee "/etc/apt/sources.list.d/codeon.de-${debname}.list" > /dev/null

   echo "Added Codeon repository to apt" >&2
}





r_get_linux_release()
{
   RVAL="`lsb_release -c -s`"
}


r_get_debname()
{
   #
   # we can choose a different mulle-kybernetik debian repository instead
   # of "main" like say "prerelease", if the branch contains
   # &debname=prerelease.
   #
   # Yes you can use & in git tags:
   # https://git-scm.com/docs/git-check-ref-format
   #
   case "${TRAVIS_BRANCH}" in
      *'&debname='*)
         RVAL="${TRAVIS_BRANCH#*\&debname=}"
         RVAL="${RVAL%&*}"
      ;;

      # hard coded convention
      'prerelease')
         RVAL='prerelease'
      ;;

      *)
         RVAL="main"
      ;;
   esac

   #
   # use DEBIAN_REPOSITORY preferably (set it in travis-ci settings)
   #
   RVAL="${DEBIAN_REPOSITORY:-${RVAL}}"
}


r_get_hostname()
{
   case "${TRAVIS_BRANCH}" in
      *'&hostname='*)
         RVAL="${TRAVIS_BRANCH#*\&hostname=}"
         RVAL="${RVAL%&*}"
      ;;

      # hard coded convention
      'prerelease'*)
         RVAL="travis-ci-prerelease"
      ;;

      *)
         RVAL="travis-ci"
      ;;
   esac

   #
   # use MULLE_HOSTNAME preferably (set it in travis-ci settings)
   #
   RVAL="${MULLE_HOSTNAME:-${RVAL}}"
}


main()
{
   local release
   local debname

   r_get_linux_release || exit 1
   release="${RVAL}"

   r_get_debname
   debname="${RVAL}"

   r_get_hostname
   MULLE_HOSTNAME="${RVAL}"
   export MULLE_HOSTNAME

   get_mulle_kybernetik_gpg_key && \
   add_mulle_kybernetik_to_apt_sources "${release}" "${debname}" &&  \
   get_codeon_gpg_key && \
   add_codeon_to_apt_sources "${release}" "${debname}" &&  \
   sudo apt-get update && \
   sudo apt-get -y install mulle-sde mulle-test mulle-clang ${OTHER_DEBIAN_PACKAGES}
}

main "$@"
