/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 69A386D5-EA1E-4B78-BCDC-3E8D6923864B instead of MulleObjCOSFoundation if there are duplicate entries)
//    remove:             `mulle-sde dependency mark MulleObjCOSFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCOSFoundation include whatever.h`
//    reorder:            `mulle-sde dependency move MulleObjCOSFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCOSFoundation [no-]import`
//    toggle public:      `mulle-sde dependency mark MulleObjCOSFoundation [no-]public`
//    toggle optional:    `mulle-sde dependency mark MulleObjCOSFoundation [no-]require`
//    remove for platform:`mulle-sde dependency mark MulleObjCOSFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCOSFoundation/MulleObjCOSFoundation.h>   // MulleObjCOSFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCCalendarFoundation-include.h")
#  include "_MulleObjCCalendarFoundation-include.h"
# endif
#endif

