      { @selector( MulleObjCDeps), @selector( MulleObjCOSFoundation) },      // 3c20656f;MulleObjCDeps;94ffe970;MulleObjCOSFoundation
      { @selector( NSCalendar), @selector( NSDate) },      // e4a20882;NSCalendar;cfcedd21;NSDate
      { @selector( NSCalendar), @selector( _MulleGregorianCalendar) },      // e4a20882;NSCalendar;db7623b3;_MulleGregorianCalendar
      { @selector( NSCalendar), MULLE_OBJC_NO_CATEGORYID },      // e4a20882;NSCalendar;;
      { @selector( NSDateComponents), MULLE_OBJC_NO_CATEGORYID },      // 58cf266a;NSDateComponents;;
      { @selector( _MulleGregorianCalendar), MULLE_OBJC_NO_CATEGORYID },      // db7623b3;_MulleGregorianCalendar;;
      { @selector( _MulleJulianCalendar), MULLE_OBJC_NO_CATEGORYID },      // 0e8fad4b;_MulleJulianCalendar;;
