      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCLockFoundation) },      // 47a9beb6;MulleObjCLoader;86a97828;MulleObjCLockFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSFoundation) },      // 47a9beb6;MulleObjCLoader;94ffe970;MulleObjCOSFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCPlistFoundation) },      // 47a9beb6;MulleObjCLoader;e8aa8d92;MulleObjCPlistFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCTimeFoundation) },      // 47a9beb6;MulleObjCLoader;cc20d48b;MulleObjCTimeFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( NSCalendar), @selector( NSDate) },      // e4a20882;NSCalendar;cfcedd21;NSDate
      { @selector( NSCalendar), @selector( _MulleGregorianCalendar) },      // e4a20882;NSCalendar;db7623b3;_MulleGregorianCalendar
      { @selector( NSCalendar), MULLE_OBJC_NO_CATEGORYID },      // e4a20882;NSCalendar;;
      { @selector( NSDateComponents), @selector( NSString) },      // 58cf266a;NSDateComponents;1994a171;NSString
      { @selector( NSDateComponents), MULLE_OBJC_NO_CATEGORYID },      // 58cf266a;NSDateComponents;;
      { @selector( _MulleGregorianCalendar), MULLE_OBJC_NO_CATEGORYID },      // db7623b3;_MulleGregorianCalendar;;
      { @selector( _MulleJulianCalendar), MULLE_OBJC_NO_CATEGORYID },      // 0e8fad4b;_MulleJulianCalendar;;
