#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/Parsing
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_HEADERS
src/_MulleGregorianCalendar.h
src/_MulleJulianCalendar.h
src/MulleObjCCalendarFoundation.h
src/MulleObjCLoader+MulleObjCCalendarFoundation.h
src/NSCalendar+NSDate.h
src/NSCalendar.h
src/NSDateComponents.h
src/NSPropertyListSerialization+ICU.h
src/Parsing/NSObject+ICUPropertyListParsing.h
src/Parsing/NSString+ICUPropertyListParsing.h
src/import.h
)

