#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/_MulleGregorianCalendar.m
src/_MulleJulianCalendar.m
src/MulleObjCCalendarFoundation.m
src/NSCalendar+NSDate.m
src/NSCalendar.m
src/NSDateComponents+NSString.m
src/NSDateComponents.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCCalendarFoundation.m
)
